version: '3.9'
services:
  gwmulti_rest:
    image: "go-whatsapp-multidevice-rest:latest"
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: 'always'
    ports:
      - "3000:3000"